### PR TITLE
declare type of step in advance*.

### PR DESCRIPTION
**Pull request by rudolph-miller**

### CODE REVIEW

**Comment by fukamachi** [comment]
I don't get why this change has to be in. The `step` could be a symbol or a form.

**Comment by rudolph-miller** [comment]
with `(declare (speed 3) (safety 0) (debug 0))` compiler said `step` is uncertain.
Can `step` be symbol or form?

**Comment by fukamachi** [comment]
Yes, cause `advance*` is a macro. 

You're declaring it compile-time. If the warning disappears by this, it's not important, just you're making it unsafe expansion. 

Are there any differences in performance?

**Comment by rudolph-miller** [comment]
I know it has no influence on performance and it's just matter of compilation time.
I wanna just remove warnings.
Does the change make it unsafer?

**Comment by fukamachi** [comment]
There must be other warnings in compile-time too. Declaring `speed 0` in the macros would work, I think.

**Comment by rudolph-miller** [comment]
Really?
I can not remove warnings with `speed 0` in macros.
Anyway, I can ignore the warnings with compilation time.

**Pull request closed without merging**
